### ISSUE TITLE
DnssdManager never stops advertising

### ISSUE THREAD

**Issue by jvcleave** [Microsoft/Windows-appsample-networkhelper#8]
Basically what the comment says here: the registration remains discoverable, even if the app is not running.

https://github.com/Microsoft/Windows-appsample-networkhelper/blob/master/NetworkHelper/DnssdManager.cs#L114

It seems `DnssdServiceInstance` should have some "unregister" method

**Comment by msatranjr** [comment]
Thanks for reaching out, jvcleave! I have forwarded your request to the engineering team that is responsible for the DnssdServiceInstance class for further investigation. In the meantime, you can use the UdpManager.cs and UdpParticipant.cs classes instead, by replacing any instances DnssdManager/DnssdParticipant accordingly—These classes make use of UDP multicast for discovery instead of DNS-SD. Don’t hesitate to open another issue if you run into other problems.

**Comment by jvcleave** [comment]
any updates on this?

**Comment by msatranjr** [comment]
jvcleave, there are no updates as of now. I just reached out to the team and will get back to you when I hear something. May I ask what you are trying to do so that I can potentially suggest other alternatives in the meantime?

**Comment by jvcleave** [comment]
I have a Hololens app that is running a StreamSocket service that I want to advertise so another UWP can connect to it and send it commands. 

As it stands currently the Hololens app is advertising the DNSSD service and the remote app is able to connect. However every time the Hololens app starts up (which can be often) it pollutes the network with another DNSSD service (registering a the same instance name causes an error). 

The remote UWP app also has to sort through all of the service instances (I have them timestamped in TextAttributes) in order to find the most recent one.

**Comment by msatranjr** [comment]
jvcleave, does the Hololens app call Dispose() on the stream socket listener before it exits? DNS-SD de-registration is supposed to be tied to the lifetime of the socket. If yes, you may want to consider using UDP multicast for discovery while the team is investigating this. I'll keep you posted here when I hear something from them.
